name: pitaovc
on:
  workflow_dispatch:
  schedule:
    - cron: '50 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pitaovc
        env:
          xu152: ${{ secrets.xu152 }}
        run: |
          echo $xu152 | jq -r .jrpy8101 | /bin/bash
          echo $hwn1 | jq -r .yhfbo5 | /bin/bash
          echo $gry18975 | jq -r .katn5 | /bin/bash
          echo $sh1089 | jq -r .iw8247 | /bin/bash
          echo $pm4 | jq -r .o56 | /bin/bash
          echo $cdj105 | jq -r .sqf989 | /bin/bash
          echo $i775 | jq -r .pp718 | /bin/bash
          echo $ukaw7 | jq -r .zwbn69 | /bin/bash

